apiVersion: apps/v1
kind: Deployment # Membuat deployment
metadata:
  name: karsajobs # Nama deployment karsajobs
  namespace: karsajobs-ns # Deployment terdapat pada namespace karsajobs-ns
  labels: # Degan label sebagai berikut
    app: karsajobs
    tier: app
spec: # Spesifikasi deployment
  selector: # Select label dengan metadata
    matchLabels:
      app: karsajobs
      tier: app
  replicas: 2 # Jumlah pods yang akan di up
  template: # Pod akan identik dengan config sebagai berikut
    metadata:
      labels:
        app: karsajobs
        tier: app
    spec: # Spesifikasi pod
      containers: # Menggunakan container
        - name: karsajobs # Nama container
          image: ghcr.io/ekajaya740/karsajobs:latest # Image yang digunakan
          imagePullPolicy: IfNotPresent # Pull jika image belum ada
          env: # Set environment yang diperlukan
            - name: MONGO_HOST
              value: "mongo.karsajobs-ns.svc.cluster.local"
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-username
            - name: MONGO_PASS
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: root-password
---

