# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-deployment
  namespace: default
  labels:
    app: order-service
    istio: ingressgateway
spec:
  selector:
    matchLabels:
      app: order-service
      istio: ingressgateway
  replicas: 1
  template:
    metadata:
      labels:
        app: order-service
        istio: ingressgateway
    spec:
      containers:
        - name: order-service-app
          image: ghcr.io/ekajaya740/order-service:latest
          imagePullPolicy: Always
          resources:
          env:
            - name: PORT
              value: "3000"
            - name: AMQP_URL
              value: "amqp://user:0uovT6jbfAa9TWep@rabbitmq.rabbitmq:5672"
          ports:
            - containerPort: 3000
      restartPolicy: Always
---

