apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: karsajobs-ns
spec:
  clusterIP: None
  selector:
    app: mongo
    tier: data
  type:
  ports:
    - port: 27017
      targetPort: 21017
---

