apiVersion: apps/v1
kind: StatefulSet # Membuat StatefulSet
metadata:
  name: mongo # Nama StatefulSet
  namespace: karsajobs-ns # StatefulSet terdapat pada namespace
  labels: # Dengan label sebagai berikut
    app: mongo
spec: # Spesifikasi StatefulSet
  selector: # Select dengan label berikut
    matchLabels:
      app: mongo
      tier: data
  serviceName: mongo # Nama StatefulSet adalah mongo
  replicas: 1 # Jumlah pod yang akan di up
  template: # Dengan template pod sebagai berukut
    metadata:
      labels:
        app: mongo
        tier: data
    spec: # Spesifikasi pod
      terminationGracePeriodSeconds: 10 # Pod akan shutdown dalam 10 detik jika tershutdown
      containers: # Menggunakan container
        - name: mongo # Nama container adalah mongo
          image: mongo:latest # Dengan image mongo:latest
          env: # Set env yang diperlukan
            - name: MONGO_INITDB_ROOT_USERNAME_FILE
              value: /etc/mongo-credentials/MONGO_ROOT_USERNAME
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: /etc/mongo-credentials/MONGO_ROOT_PASSWORD
          ports: # Expose port
            - containerPort: 27017
              name: mongo
          volumeMounts: # Mount ke PV
            - name: mongo-pv
              mountPath: /data/db
            - name: mongo-config
              mountPath: /config
            - name: mongo-secret
              mountPath: /etc/mongo-credentials
      volumes: # Koneksi ke PVC
        - name: mongo-config
          configMap:
            name: mongo-config
        - name: mongo-secret
          secret:
            secretName: mongo-secret
        - name: mongo-pv
          persistentVolumeClaim:
            claimName: mongo-pv-claim
