apiVersion: v1
kind: ConfigMap # Membuat ConfigMap
metadata:
  name: mongo-config # Nama ConfigMap
  namespace: karsajobs-ns # Terdapat pada namespace karsajobs-ns
data: # Berikut list ConfigMap yang akan diterapkan
  mongod.conf: |
    storage:
      dbPath: /data/db
      journal:
        enabled: true
    systemLog:
      destination: file
      path: /var/log/mongodb/mongod.log
      logAppend: true
    security:
      authorization: enabled
