apiVersion: v1
kind: Service # Membuat service
metadata:
  name: mongo # Nama service
  namespace: karsajobs-ns # Service terdapat pada namespace karsajobs-ns
spec:
  clusterIP: None # Service berupa headless service
  selector: # Select service dengan spesifikasi sebagai berikut
    app: mongo
    tier: data
  type:
  ports: # Expose port
    - port: 27017
      targetPort: 21017
---

