apiVersion: v1
kind: Secret # Membuat secret
metadata:
  name: mongo-secret # Nama secret
  namespace: karsajobs-ns # Secret terdapat pada namespace karsajobs-ns
type: Opaque # Tipe dari secret
data: # Data yang ada pada secret, value di store di file ini dengan format base64
  MONGO_ROOT_USERNAME: YWRtaW4=
  MONGO_ROOT_PASSWORD: c3VwZXJzZWNyZXRwYXNzd29yZA==
