apiVersion: v1
kind: Secret # Membuat secret
metadata:
  name: mongodb-secret # Nama secret
  namespace: karsajobs-ns # Secret terdapat pada namespace karsajobs-ns
type: Opaque # Tipe dari secret
data: # Data yang ada pada secret, value di store di file ini dengan format base64
  root-username: cm9vdA==
  root-password: MTIzNDU2
