# https://kubernetes.io/docs/concepts/workloads/controllers/deployment/
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping-service-deployment
  namespace: default
  labels:
    app: shipping-service
spec:
  selector:
    matchLabels:
      app: shipping-service
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping-service
    spec:
      containers:
        - name: shipping-service-app
          image: ghcr.io/ekajaya740/shipping-service:latest
          imagePullPolicy: Always
          resources:
          env:
            - name: PORT
              value: "3001"
            - name: AMQP_URL
              value: "amqp://user:0uovT6jbfAa9TWep@rabbitmq.rabbitmq:5672"
          ports:
            - containerPort: 3001
      restartPolicy: Always
---

