# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: shipping-service-svc
  namespace: default
spec:
  selector:
    app: shipping-service
  type: NodePort
  ports:
    - name: http
      port: 3001
      targetPort: 3001
      nodePort: 30001
---

